import Icon from 'react-native-vector-icons/MaterialCommunityIcons';

export const PRODUCTS_ITEMS = [
  {     
    id: 1,
    icon: <Icon name="dropbox" color={'blue'} size={30} />,
    name: 'Checkbox plan',
    name1: "CheckBox",
    name2: "Large Balloton" ,
    price: "$144.00",
    secondVal: '($300.00 Deposit)',
    clr: "+ colors"
  },
  {     
    id: 2,
    icon: <Icon name="music" color={'blue'} size={30} />,
    name: 'Spotify',
    name1: "Spotify",
    name2: "Large Satin" ,
    price: "$24.00",
    secondVal: '($300.00 Deposit)',
  },
  {     
    id: 3,
    icon: <Icon name="youtube" color={'blue'} size={30} />,
    name: 'MytubeAds',
    name1: "MytubeAds",
    name2: "Large Satin" ,
    price: "$24.00",
    secondVal: '($300.00 Deposit)',
  },
  {     
    id: 4,
    icon: <Icon name="briefcase" color={'blue'} size={30} />,
    name: 'FreelanceWork',
    name1: "FreelanceWork",
    name2: "Large Satin" ,
    price: "$24.00",
    secondVal: '($300.00 Deposit)',
  },
  {     
    id: 5,
    icon: <Icon name="contactless-payment" color={'blue'} size={30} />,
    name: 'payment',
    name1: "payment",
    name2: "Large Satin" ,
    price: "$24.00",
    secondVal: '($300.00 Deposit)',
  },
  {     
    id: 6,
    icon: <Icon name="dropbox" color={'blue'} size={30} />,
    name: 'Checkbox plan',
    name1: "CheckBox",
    name2: "Large Balloton" ,
    price: "$144.00",
    secondVal: '($300.00 Deposit)',
    clr: "+ colors"
  },
  {     
    id: 7,
    icon: <Icon name="music" color={'blue'} size={30} />,
    name: 'Spotify',
    name1: "Spotify",
    name2: "Large Satin" ,
    price: "$24.00",
    secondVal: '($300.00 Deposit)',
  },
  {     
    id: 8,
    icon: <Icon name="youtube" color={'blue'} size={30} />,
    name: 'MytubeAds',
    name1: "MytubeAds",
    name2: "Large Satin" ,
    price: "$24.00",
    secondVal: '($300.00 Deposit)',
  },
  {     
    id: 9,
    icon: <Icon name="briefcase" color={'blue'} size={30} />,
    name: 'FreelanceWork',
    name1: "FreelanceWork",
    name2: "Large Satin" ,
    price: "$24.00",
    secondVal: '($300.00 Deposit)',
  },
];
